// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDS-Zlf5Vn2SYYNIj3iEz3_E9Pt5WiyG8',
    appId: '1:27841319846:web:b79120321ae1b5e21af567',
    messagingSenderId: '27841319846',
    projectId: 'hinvex-29819',
    authDomain: 'hinvex-29819.firebaseapp.com',
    storageBucket: 'hinvex-29819.appspot.com',
    measurementId: 'G-Z8FKZF46YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmgrqhOtbjmVUI0sTFl5gkWmwN_9mFhnw',
    appId: '1:27841319846:android:5f4d62103374cb9f1af567',
    messagingSenderId: '27841319846',
    projectId: 'hinvex-29819',
    storageBucket: 'hinvex-29819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIauavIk5plV7nwMAb2jZDsCcP8tLih8o',
    appId: '1:27841319846:ios:eab635bf25ba45bf1af567',
    messagingSenderId: '27841319846',
    projectId: 'hinvex-29819',
    storageBucket: 'hinvex-29819.appspot.com',
    iosBundleId: 'com.example.hinvex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIauavIk5plV7nwMAb2jZDsCcP8tLih8o',
    appId: '1:27841319846:ios:2ebeaf8c62ee02a71af567',
    messagingSenderId: '27841319846',
    projectId: 'hinvex-29819',
    storageBucket: 'hinvex-29819.appspot.com',
    iosBundleId: 'com.example.hinvex.RunnerTests',
  );
}
